### ISSUE TITLE
initManager 不会主动开启蓝牙模块

### ISSUE THREAD

**Issue by binfengi** [apicloudcom/ble#1]
建议添加开启蓝牙代码
mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
            if (!mBluetoothAdapter.isEnabled()) {
                Intent enableBtIntent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                startActivityForResult(enableBtIntent, REQUEST_ENABLE_BT);
                return;
            }

**Comment by LPQingFeiDeYi** [comment]
ios connet方法 连接第一次是成功的，第二次连接失败，必须手动忽略设备才能重新连接。android是没有问题的。
我的分析的ios的必须要ble.getPeripheral扫描到设备的后才能连接，而事实上设备和手机已经连接的情况下，ble.getPeripheral是无法扫描到的。这样导致无法二次连接。而android是没扫描到还是可以连接的，所以这个可能是ios模块的一个bug.

**Comment by sunzhengcuan** [comment]
新版本已添加。需求可以在APICloud官方论坛发帖提出。此处仅交流模块开发相关问题
