### ISSUE TITLE
ios 连接的bug

### ISSUE THREAD

**Issue by LPQingFeiDeYi** [apicloudcom/ble#2]
ios connet方法 连接第一次是成功的，第二次连接失败，必须手动忽略设备才能重新连接。android是没有问题的。
我的分析的ios的必须要ble.getPeripheral扫描到设备的后才能连接，而事实上设备和手机已经连接的情况下，ble.getPeripheral是无法扫描到的。这样导致无法二次连接。而android是没扫描到还是可以连接的，所以这个可能是ios模块的一个bug.

**Comment by sunzhengcuan** [comment]
先断开连接再连接。模块问题要在APICloud官方论坛发帖提问。此处仅供模块开发讨论。
