### ISSUE TITLE
ble模块怎么样才能一直刷新附近可以搜索到的蓝牙

### ISSUE THREAD

**Issue by caoyq0521** [apicloudcom/ble#4]
ble模块中怎么样才能一直刷新附近可以搜索到的蓝牙，用了setInterval( getPeripheral,2000)方法，但是好像每次输出的值都是一样的，在已连接蓝牙的情况下手动关闭了蓝牙可是，
getPeripheral()函数输出的值却并没有少掉对应的蓝牙，有回帖说添加stopScan（），可我试过了还是不行，请问该怎么办？

**Comment by sunzhengcuan** [comment]
iOS上还是Android上？可以到APICloud官方论坛发帖提问，会有相关技术支持回答的。
