### ISSUE TITLE
蓝牙连接报错

### ISSUE THREAD

**Issue by deng-cell** [apicloudcom/ble#7]
ble.connect()连接蓝牙设备时报错如下：
code: -1， detailErrorCode: status: 133
请问 133 代表的是什么错误；要怎么解决

**Comment by sunzhengcuan** [comment]
callback(ret, err)返回的所有信息发下

**Comment by deng-cell** [comment]
{“code”: -1， “peripheralUUID“:“BE: EF: BE: EF E1:1E”，"detailErrorCode ": "status:133”｝

**Comment by sunzhengcuan** [comment]
这是iOS还是Android，模块问题要到APICloud官方论坛发帖提问。GitHub仅回答模块开发相关问题，。

**Comment by deng-cell** [comment]
Android，问了，没有解决

**Comment by sunzhengcuan** [comment]
你把帖子地址发下，我发给相关同事解决

**Comment by deng-cell** [comment]
detailErrorCode 这个有没有具体返回值说明

**Comment by sunzhengcuan** [comment]
你在APICloud官方论坛上提出此问题的帖子的地址

**Comment by deng-cell** [comment]
仅凭少量信息无法确定。可能是硬件问题。


这个是给我的回复

**Comment by sunzhengcuan** [comment]
那你问问他还需要提供什么信息。有必要提供硬件，邮寄地址：北京市朝阳区酒仙桥东路9号院-1号楼206模块研发部

**Comment by deng-cell** [comment]
好的，谢谢
